### ISSUE TITLE
Add style for focus class

### ISSUE THREAD

**Issue by csvenja** [csvenja/bitter-tea#1]

**Comment by NIGHTAA** [comment]
给定两个长度分别为 𝑛, 𝑚 的整数 𝑎, 𝑏，计算它们的和。
但是要注意的是，这里的 𝑎, 𝑏 采用了某种特殊的进制表示法。
最终的结果也会采用该种表示法。具体而言，从低位往高位数起，
第 𝑖 位采用的是 𝑖 + 1 进制。换言之，相较于十进制下每一位的
「逢 10 进 1」，该种进制下第 𝑖 位是「逢 𝑖 + 1 进 1」。
